=== mrphemi/csym2019_assignment/Task1/weatherschema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://example.com/object1620402386.json",
  "title": "Root",
  "type": "array",
  "default": [],
  "items": {
    "$id": "#root/items",
    "title": "Items",
    "type": "object",
    "required": [
      "city_id",
      "city_name",
      "current_conditions",
      "temperature",
      "wind"
    ],
    "properties": {
      "city_id": {
        "$id": "#root/items/city_id",
        "title": "City_id",
        "type": "integer",
        "examples": [1],
        "default": 0
      },
      "city_name": {
        "$id": "#root/items/city_name",
        "title": "City_name",
        "type": "string",
        "default": "",
        "examples": ["London"],
        "pattern": "^.*$"
      },
      "current_conditions": {
        "$id": "#root/items/current_conditions",
        "title": "Current_conditions",
        "type": "string",
        "default": "",
        "examples": ["cloudy"],
        "pattern": "^.*$"
      },
      "temperature": {
        "$id": "#root/items/temperature",
        "title": "Temperature",
        "type": "object",
        "required": ["celcius", "fahrenheit"],
        "properties": {
          "celcius": {
            "$id": "#root/items/temperature/celcius",
            "title": "Celcius",
            "type": "integer",
            "examples": [13],
            "default": 0
          },
          "fahrenheit": {
            "$id": "#root/items/temperature/fahrenheit",
            "title": "Fahrenheit",
            "type": "number",
            "examples": [55.4],
            "default": 0.0
          }
        }
      },
      "wind": {
        "$id": "#root/items/wind",
        "title": "Wind",
        "type": "object",
        "required": ["wind_speed", "wind_direction", "wind_chill_factor"],
        "properties": {
          "wind_speed": {
            "$id": "#root/items/wind/wind_speed",
            "title": "Wind_speed",
            "type": "integer",
            "examples": [9],
            "default": 0
          },
          "wind_direction": {
            "$id": "#root/items/wind/wind_direction",
            "title": "Wind_direction",
            "type": "integer",
            "examples": [45],
            "default": 0
          },
          "wind_chill_factor": {
            "$id": "#root/items/wind/wind_chill_factor",
            "title": "Wind_chill_factor",
            "type": "number",
            "examples": [2.5],
            "default": 0.0
          }
        }
      }
    }
  }
}

=== mrphemi/csym2019_assignment/Task1/weather.json
[
  {
    "city_id": 1,
    "city_name": "London",
    "current_conditions": "cloud",
    "temperature": {
      "celcius": 13,
      "fahrenheit": 55.4
    },
    "wind": {
      "wind_speed": 9,
      "wind_direction": 45,
      "wind_chill_factor": 2.5
    }
  },
  {
    "city_id": 2,
    "city_name": "Manchester",
    "current_conditions": "sleet",
    "temperature": {
      "celcius": 12,
      "fahrenheit": 53.6
    },
    "wind": {
      "wind_speed": 11,
      "wind_direction": 300,
      "wind_chill_factor": 4.5
    }
  },
  {
    "city_id": 3,
    "city_name": "Liverpool",
    "current_conditions": "thunderstorm",
    "temperature": {
      "celcius": 9,
      "fahrenheit": 48.2
    },
    "wind": {
      "wind_speed": 17,
      "wind_direction": 67,
      "wind_chill_factor": 1.2
    }
  },
  {
    "city_id": 4,
    "city_name": "Milton Keynes",
    "current_conditions": "sun",
    "temperature": {
      "celcius": 15,
      "fahrenheit": 59
    },
    "wind": {
      "wind_speed": 5,
      "wind_direction": 180,
      "wind_chill_factor": 3.2
    }
  },
  {
    "city_id": 5,
    "city_name": "Dartford",
    "current_conditions": "heavy rain",
    "temperature": {
      "celcius": 11,
      "fahrenheit": 43
    },
    "wind": {
      "wind_speed": 8,
      "wind_direction": 125,
      "wind_chill_factor": 4.6
    }
  }
]
